name: Build Custom wasm-opt.wasm
on: 
  workflow_dispatch:
    inputs:
      with_custom_pass:
        description: 'Inject InjectYields.cpp pass'
        required: true
        type: boolean
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout my repo
        uses: actions/checkout@v4
        with:
          path: 'my-repo'

      - name: Checkout Binaryen
        uses: actions/checkout@v4
        with: 
          repository: 'WebAssembly/binaryen'
          path: 'binaryen'
          fetch-depth: 1
          submodules: recursive
          
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: binaryen-wasi-ccache-${{ inputs.with_custom_pass }}
          
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build
          # Download WASI SDK 33
          wget https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-33/wasi-sdk-33.0-x86_64-linux.tar.gz
          tar xvf wasi-sdk-33.0-x86_64-linux.tar.gz

      - name: Inject Custom Pass into Binaryen
        if: ${{ inputs.with_custom_pass }}
        run: |
          cp my-repo/InjectYields.cpp binaryen/src/passes/
          cd binaryen
          sed -i '/src\/passes\/Asyncify.cpp/a \  src/passes/InjectYields.cpp' CMakeLists.txt
          sed -i '/namespace wasm {/a Pass* createInjectYieldsPass();' src/passes/pass.cpp
          sed -i '/registerPass("asyncify"/a \  registerPass("inject-yields", "Injects cooperative yielding checks", createInjectYieldsPass);' src/passes/pass.cpp

      - name: Build
        run: |
          cd binaryen
          mkdir build && cd build

          # Hartwork's workaround: Patch the target directly inside the pthread toolchain file!
          sed -i 's/wasm32-wasi/wasm32-wasip1/g' $GITHUB_WORKSPACE/wasi-sdk-33.0-x86_64-linux/share/cmake/wasi-sdk-pthread.cmake
          
          # Notice the updated paths pointing to the wasi-sdk-33.0-x86_64-linux folder
          cmake .. -G Ninja \
                   -DCMAKE_TOOLCHAIN_FILE=$GITHUB_WORKSPACE/wasi-sdk-33.0-x86_64-linux/share/cmake/wasi-sdk-pthread.cmake \
                   -DWASI_SDK_PREFIX=$GITHUB_WORKSPACE/wasi-sdk-33.0-x86_64-linux \
                   -DBUILD_TOOLS=ON \
                   -DBUILD_TESTS=OFF \
                   -DBUILD_SHARED_LIBS=OFF \
                   -DBUILD_STATIC_LIB=ON \
                   -DCMAKE_BUILD_TYPE=Release \
                   -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
                   -DCMAKE_CXX_FLAGS="-pthread -fwasm-exceptions"
                   
          ninja wasm-opt -j4
          
      - uses: actions/upload-artifact@v4
        with:
          name: wasm-opt-binary
          path: binaryen/build/bin/wasm-opt
